document.getElementById("main").childNodes[0].style = "max-width: 800px; margin-left: auto; margin-right: auto";
document.getElementById("extensions").style.setProperty("max-width", "800px");
document.getElementById("extensions").style.setProperty("margin-left", "auto");
document.getElementById("extensions").style.setProperty("margin-right", "auto");

setTimeout(function() {
document.querySelector("#component-278 > div.tab-nav.scroll-hide.svelte-1g805jl.header_bar > button:nth-child(1)").textContent = "генерация текста";
document.querySelector("#component-278 > div.tab-nav.scroll-hide.svelte-1g805jl.header_bar > button:nth-child(2)").textContent = "персонаж";
document.querySelector("#component-278 > div.tab-nav.scroll-hide.svelte-1g805jl.header_bar > button:nth-child(3)").textContent = "параметры";
document.querySelector("#component-278 > div.tab-nav.scroll-hide.svelte-1g805jl.header_bar > button:nth-child(4)").textContent = "модель";
document.querySelector("#component-278 > div.tab-nav.scroll-hide.svelte-1g805jl.header_bar > button:nth-child(5)").textContent = "тренировка";
document.querySelector("#component-278 > div.tab-nav.scroll-hide.svelte-1g805jl.header_bar > button:nth-child(6)").textContent = "настройки интерфейса";
document.querySelector("#component-5 > label > span").textContent = "промпт";
document.querySelector("#stop").textContent = "стоп";
document.querySelector("#Generate").textContent = "генерировать";
document.querySelector("#component-9").textContent = "продолжить";
document.querySelector("#component-11").textContent = "копировать последний ответ";
document.querySelector("#component-12").textContent = "перегенерировать";
document.querySelector("#component-13").textContent = "замена последнего ответа";
document.querySelector("#component-15").textContent = "выдавать себя за";
document.querySelector("#component-16").textContent = "фейковый промпт";
document.querySelector("#component-17").textContent = "фейковый ответ";
document.querySelector("#component-19").textContent = "удалить последний";
document.querySelector("#component-20").textContent = "очистить историю";
document.querySelector("#component-23 > span").textContent = "режим";
document.querySelector("#component-272 > h3").textContent = "галерея";
document.querySelector("#component-273 > div.label-wrap.svelte-s1r2yt > span:nth-child(1)").textContent = "галерея персонажей";
document.querySelector("#component-30 > label > span").textContent = "твой имярек";
document.querySelector("#component-31 > label > span").textContent = "имя бота";
document.querySelector("#component-32 > label > span").textContent = "приветсвие";
document.querySelector("#component-33 > label > span").textContent = "контекст";
document.querySelector("#component-34 > label > span").textContent = "включить шаблон";
document.querySelector("#component-34 > label > div").textContent = "точное определения размещения пробелов и символов новой строки в промптах";
document.querySelector("#character-menu > label > span").textContent = "персонаж";
document.querySelector("#component-64 > div.tab-nav.scroll-hide.svelte-1g805jl > button:nth-child(1)").textContent = "история чата";
document.querySelector("#component-46 > p").textContent = "загрузить";
document.querySelector("#component-49 > p").textContent = "скачать";
document.querySelector("#component-51").textContent = "нажми сюда";
document.querySelector("#component-64 > div.tab-nav.scroll-hide.svelte-1g805jl > button:nth-child(2)").textContent = "загрузить персонажа";
}, 4000);